### ISSUE TITLE
[BUG] “View APP IDs” doesn‘t allign with “My App“ page

### ISSUE THREAD

**Issue by qhgary** [SideStore/SideStore#267] opened 2023-02-16 23:21 UTC
### Describe the bug

“view app IDs“ page showed the left days apps can be used, however even I successfully refreshed all the apps, “my app“ page reset all the apps to 7 days, but “view app IDs“ didn‘t.

### Instructions to reproduce

![36B4DC88-80E7-4F2D-B95E-904C8EAF499F](https://user-images.githubusercontent.com/12314068/219510141-f2c582e2-c882-4143-85ef-eb0cc5f84162.png)
![8E2F734B-1BB2-4CFC-BE2F-11A1ACA22A04](https://user-images.githubusercontent.com/12314068/219510154-0dc7e7d8-a441-4a6a-afb0-3e795f3ad1c2.png)

### What version of SideStore are you using?

0.3 nightly 14

**Comment by qhgary** [comment] 2023-02-23 03:50
This bug makes the sidestore app not work at all. Although the apps have been refreshed successfully, the actual “7days count down“ still continues. 

Is the bug related to the version of ios or sidestore? I‘d like to ask whether there is anyone working on this issue and the reason to this. Thanks a lot.

**Comment by naturecodevoid** [comment] 2023-02-23 05:15
My guess is that it's related to duplicate provisioning profiles, which we are working on fixing. I've seen some people that have 11 app IDs. This issue doesn't seem to be causing any major issues, so no one has investigated it. If your SideStore expired early/randomly, that's duplicate provisioning profiles.

**Comment by qhgary** [comment] 2023-02-23 05:49
I have two IDs and I habe no idea what does “two provisioning profiles” mean. Could you help to just tell me how to get rid of the duplicated profile manually? I‘ve already tried to remove sidestore and reinstall it but in vain.

**Comment by theoccurrence** [comment] 2023-02-23 10:43
> This bug makes the sidestore app not work at all. Although the apps have been refreshed successfully, the actual “7days count down“ still continues. 
> 


I'm not sure if I understood your problem correctly, but this is expected behavior. You can neither refresh nor delete App IDs. That's what it says on one of your screenshots, so I'm not sure if I understood your problem correctly.

"App IDs can't be deleted, but they do expire
after one week. SideStore will automatically
renew App IDs for all active apps once they've
expired."

Maybe you describe your problem again in other words so I understand what you mean.

**Comment by qhgary** [comment] 2023-02-23 14:18
the problem is:
sidestore & uyou can be reset to 7 days if I click “refresh“ button in “my apps“ page.
however, the count down continues in “app ids“ page. You said it was expected behavior and they do expire in one week. I understood that. But you said “sidestore will automatically renew apple ids for all active apps“ I couldn't see that. what I saw was that “sidestore“ cannot be open again in 7 days although I refreshed sidestore successfully(reset to 7 in my apps page) every day.

**Comment by theoccurrence** [comment] 2023-02-23 15:29
> however, the count down continues in “app ids“ page. You said it was expected behavior and they do expire in one week. I understood that. But you said “sidestore will automatically renew apple ids for all active apps“ I couldn't see that.

That's literally what it says at the top of one of your screenshots. App IDs have nothing to do with Apps sideloaded on your Device, you can register 10 App IDs every week, but you can only install 3 at a time.

Sidestore randomly unsigning is a bug that has nothing to do with App IDs. If you get this bug and want to avoid it, you can try sideloading sidestore again instead of refreshing. But don't use your PC for that, just install a SideStore.ipa with SideStore. Like you would for an update.

**Comment by naturecodevoid** [comment] 2023-02-24 16:40
SideStore randomly becoming unavailable or expiring before 7 days even after refreshing is duplicate provisioning profiles; it has nothing to do with the app IDs page. I'll probably close this issue soon since it seems to be a duplicate of the duplicate provisioning profiles issue. We are working on a fix (I actually made one already, but there are some issues with it that I haven't been able resolve)

**Closed** 2023-02-24 16:54 UTC
Labels: bug
