### ISSUE TITLE
[BUG] Is this Normal? (Sidestore wants me to update to an older version)

### ISSUE THREAD

**Issue by Luminex23** [SideStore/SideStore#682] opened 2024-08-25 20:46 UTC
### Describe the bug

Hello I installed sidestore and a few days later i have the august update available i installed it and now it wants to update to the april update
![IMG_7585](https://github.com/user-attachments/assets/06a412c4-7d52-4f9e-acad-2c5f1796ac9b)

### Instructions to reproduce

Update the app to the august version without using the pc method

### What version of SideStore are you using?

0.5.7

**Comment by SternXD** [comment] 2024-08-26 03:18
Duplicate of #666

**Closed by SternXD** 2024-08-26 03:18 UTC
Labels: bug
