### ISSUE TITLE
[BUG] Unable to Launch SideStore

### ISSUE THREAD

**Issue by xArdyce** [SideStore/SideStore#292] opened 2023-03-07 05:08 UTC
### Describe the bug

I’ve installed the new sidestore update but the application does not want to launch instead i get met with an error. I’ve done this with both Regular and Beta and the results are the same 
![741A0994-308F-4FFA-831F-367651CB41C7](https://user-images.githubusercontent.com/127175453/223325873-c68da872-e022-4cc6-b61a-894ed73faf7a.png)

### Instructions to reproduce

Install latest SideStore with Altstore

### What version of SideStore are you using?

Release 0.3.1

**Comment by Spidy123222** [comment] 2023-03-07 06:53
Duplicate of https://github.com/SideStore/SideStore/issues/222

**Closed** 2023-03-07 06:53 UTC
Labels: bug

**Comment by xArdyce** [comment] 2023-03-07 14:22
> Duplicate of #222

but they used sideloady and that was the reason why their app wasn’t working as intended, i didn’t. i used altstore like recommended

**Comment by naturecodevoid** [comment] 2023-03-07 15:16
Don't use altstore, use AltServer.

**Comment by xArdyce** [comment] 2023-03-07 15:19
> Don't use altstore, use AltServer.

…..altserver installs altstore which is used to install sidestore

**Comment by shadoez** [comment] 2023-03-31 22:07
> Don't use altstore, use AltServer.

getting same error. I thought AltServer only Installed altstore. How to make it install something else?

**Comment by xArdyce** [comment] 2023-03-31 22:48
shift click on the altserver to install different ipa’s

**Comment by xArdyce** [comment] 2023-03-31 22:48
> > Don't use altstore, use AltServer.
> 
> getting same error. I thought AltServer only Installed altstore. How to make it install something else?

shift click on the altserver icon to install different ipa’s

**Comment by Dan2TDMJace** [comment] 2023-05-25 17:38
What @xArdyce mentioned gives me an error:
"remove_all: Access is denied." and a file path.

**Comment by Dan2TDMJace** [comment] 2023-05-25 17:39
AltServer also crashes.

**Comment by naturecodevoid** [comment] 2023-05-25 18:09
altserver bug, report it to altstore, not here
