### ISSUE TITLE
[问题] Some files cannot be installed, but altstore can

### ISSUE THREAD

**Issue by DrLogicBox** [SideStore/SideStore#250] opened 2023-02-05 15:50 UTC
Some files cannot be installed, but altstore can

1. Go to 'My apps'
2. Click on '+'
3. Add my ipa
4. See error’ The app is invalid.’

 - Device: [ipad pro 2021]
 - OS: [ipados 16.3]

**Comment by naturecodevoid** [comment] 2023-02-06 03:26
Duplicate of #251? Please reopen if not

**Closed by naturecodevoid** 2023-02-06 03:26 UTC
Labels: bug
