### ISSUE TITLE
[BUG] Can't install app from staging directory

### ISSUE THREAD

**Issue by andre1808** [SideStore/SideStore#270] opened 2023-02-19 12:39 UTC
### Describe the bug

I've tried the latest nightly, the 0.1.1 release, and several versions from the actions page - I just can't make this work.
I'm using a brand new, never used apple id.

Most of the time I just end up with the error "Can't install app from staging directory".
The way I'm installing is, I'm using the AltStore on my Windows PC and install SideStore from there - which is working fine.
Then I'm approving the developer account and set my selfhosted anisette server.
I connect to the "VPN", open SideStore, select the plist file and try to refresh SideStore.

Usually I will see that staging error at this point already.
I close the app and see that it's "reinstalling". I'm opening SideStore again and refresh, this time without an error.
Now I'm trying to install any app (I've been trying uyou+ and youtube elite), I get this staging error again.
The app however will install just fine. It is available from my appdrawer and working. But it's not available from the SideStore app page for refresh.

I'm kinda exhausted by now, since I've tried it several times in the past four hours. I've created 3 new apple IDs and I just can't make it work. I've even upgraded to the newest iOS version during that time.
The only thing that I haven't tried is reinstalling my phone entirely (and I hope this isn't necessary to sort this issue out?!).

I've checked in the issue reports, but those reports were about "many app installations". I'm getting this error directly from the beginning.

Do you have any idea how to fix this?

### Instructions to reproduce

it's actually in the description part.

### What version of SideStore are you using?

nightly, 0.1.1 and several version from the actions page

### Other info

I'm using an iPhone 13, now with iOS 16.3.1

**Comment by naturecodevoid** [comment] 2023-02-19 15:05
Hi, thanks for reporting this. The staging error is one of our highest priority bugs to fix. We have gotten many reports of it happening when installing uYou+. However, we've never gotten a report of it happening when you refresh an app. You should be able to manually sideload uYou+ with AltServer (you will have to do this once every 7 days if you don't want it to expire). Are you still able to reproduce it happening when you refresh? 

Also, I think it happening when you refreshed was due to you using an incomplete build from github actions. Please know that most of those builds are from incomplete PRs. One of them is a major UI rewrite and it was reported to get staging error from every install/refresh (but if you switch to the old UI, it works fine).

Please let me know if refreshing still gives a staging error (on latest nightly, not github actions builds!!). If it does, please send us minimuxer logs AFTER you reproduce it, which you can access by going to Settings > View Error Log > Click the bug icon in the top right. Otherwise, I will probably close this issue as a duplicate of the staging error issue.

**Comment by andre1808** [comment] 2023-02-19 16:44
Hi naturecodevoid.
Thanks for replying to my issue. I've created the logs and actually also recorded a video on my iPhone. If you want to see what's going on, just let me know if you want me to upload this too.

Here are the log files. One after the installation attempt of youtube elite and the other one when trying to refresh Sidestore immediatly after the installation. Both have thrown the same error again.
[minimuxer_youtubeelite.log](https://github.com/SideStore/SideStore/files/10777402/minimuxer_youtubeelite.log)
[minimuxer_Sidestore.log](https://github.com/SideStore/SideStore/files/10777403/minimuxer_Sidestore.log)

**Comment by naturecodevoid** [comment] 2023-02-19 19:34
Are you using the 16.4 beta?

**Comment by naturecodevoid** [comment] 2023-02-19 19:36
Do you have a computer that has libimobiledevice installed? It would allow us to get the rest of SideStore's logs.

**Comment by andre1808** [comment] 2023-02-19 20:02
Not on my windows PC I guess. But on my raspberry pi I think I do have it installed.
If you guide me through the process I'll try to provide those logs to you.

**Comment by naturecodevoid** [comment] 2023-02-19 20:09
1. In SideStore, go to My Apps and then view app IDs. Find the one that says `com.SideStore.SideStore.<your team id>` (NOT the one which has AltWidget it in)
2. With your device plugged into computer, run `idevicedebug run com.SideStore.SideStore.<your team id>`. (Use the text that you saw in app IDs.) Then, reproduce the error. If you want to write them to a file, do `idevicedebug run com.SideStore.SideStore.<your team id> > logs.txt` instead. Once you exit the command, the logs should be in the `logs.txt` file.

Just a warning, you will probably want to go through your logs to ensure that nothing about your Apple ID is in there. If you want to send them directly to me instead of posting them publicly here, my discord is naturecodevoid#6253.

**Comment by andre1808** [comment] 2023-02-19 21:31
hm :D 
I don't know why, but I've just installed SideStore again (just like the entire day before :)) and for some reason, now it seems to be working... Also YouTube Elite has installed just fine...

I have not changed anything. Though I was pairing my iPhone with my rpi again (and trusted it) to check if mobileidevice was installed + when I've connected it to my PC (after I've paired it to my rpi) it was asking me to trust the PC again. I did not create a new plist file or anything...

Really strange...
For now it seems to be working fine. I've refreshed both apps with no issues.

If I'm facing this problem again, I'll create the logs you were asking for.

**Closed** 2023-02-20 23:46 UTC
Labels: bug

**Comment by menotuu** [comment] 2023-03-24 23:07
I have the same fault but with sidestore 0.3.2-pr.311+875b25c

I get the „unable to install the app from the staging directory“ error.

Log
Minimuxer: https://paste.kodi.tv/ofekipohuk.kodi

Sidestore:
https://paste.kodi.tv/lowejawimo.kodi

iOS 16.3.1
