### ISSUE TITLE
[BUG] Sidestore itself won’t refresh, sometimes installs a blank icon sidestore app

### ISSUE THREAD

**Issue by kunall-ll** [SideStore/SideStore#300] opened 2023-03-13 23:45 UTC
### Describe the bug

Sidestore won’t refresh. Refreshing after the initial installation worked a couple days ago. I wanted to test an app refresh and it worked for YouTube but it won’t work for the sidestore app itself. Wireguard is on, my own anisette is running and I’ve tried using both my anisette and the preferred servers in settings. 

I’m signed in with a burner Apple ID within the sidestore app which is different to the Apple ID that I’m signed into on my phone, if that means anything. Within VPN & device management, sidestore is under the Apple ID /developer that I’m signed into on my phone. YouTube is under the burner Apple ID.

What I don’t understand is why the refresh worked the first time after sidestore installation but not now. 

![1C3135A3-B0E7-426D-B00F-BDD0F737105F](https://user-images.githubusercontent.com/26444332/224855735-76324a1c-88b4-494a-b424-1bb7481c84ca.png)
![650FE468-EC03-4B4E-9A32-F4B99D5CA857](https://user-images.githubusercontent.com/26444332/224855746-83f2da61-9532-4674-b231-b0e208bfb914.png)

### Instructions to reproduce

Wireguard on, signed into sidestore with burner Apple ID (different to one on the actual iPhone) and refreshing only sidestore. Regardless of whether you use the preferred server or your own anisette server.

### What version of SideStore are you using?

0.3.1

**Comment by naturecodevoid** [comment] 2023-03-13 23:45
duplicate of staging error

**Closed by naturecodevoid** 2023-03-13 23:45 UTC
Labels: bug

**Comment by kunall-ll** [comment] 2023-03-13 23:54
Hi, I’ve looked at the similar issues. Is there a fix or a workaround for this staging error?

**Comment by naturecodevoid** [comment] 2023-03-14 04:30
afaik no

**Comment by kunall-ll** [comment] 2023-03-14 04:48
I might delete and re-download the nightly version for now then
