### ISSUE TITLE
[FEATURE REQUEST] Enable JIT with Shortcuts or URL Schemes

### ISSUE THREAD

**Issue by Zhou-Shilin** [SideStore/SideStore#348] opened 2023-04-22 04:42 UTC
### Describe the feature

_Google Translated: Chinese -> English_
Using Shortcuts or URL Schemes to open a app with JIT.
For example,  
(URL Scheme) `sidestore://enable-jit?bundle-id=net.kdt.pojavlauncher`
(Shortcuts) `Open <app> with JIT`

### Use cases

Shortcuts (Added in the home screen):  
```
Wireguard: Open <Tunnel/SideStore>
SideStore: Open <App/Pojavlauncher>
Wireguard: Close <Tunnel/SideStore>
```

**Comment by Spidy123222** [comment] 2023-06-20 23:37
Duplicate of https://github.com/SideStore/SideStore/issues/166

**Closed** 2023-06-20 23:37 UTC
Labels: enhancement
