### ISSUE TITLE
[BUG]  an unknown error occurred (Sidestore 0.3.1)

### ISSUE THREAD

**Issue by crossholo** [SideStore/SideStore#286] opened 2023-03-04 14:50 UTC
### Describe the bug

iPhone 13 Pro Max (iOS 16.3.1)
Whenever I try to install more than one .ipa, i get this error. It’s not an .ipa issue, I tried with multiple ones, and it appears that the problem appears whenever I try to install a second one.

Here are the logs from the installation:
`SideStore.OperationError error 5`

and these ones:
```
14:30:12 [INFO] Logger initialized!!
14:30:12 [INFO] Starting heartbeat thread
14:30:17 [ERROR] Failed to create heartbeat client: UnknownError
14:30:22 [ERROR] Unable to start mobile image mounter: UnknownError
14:30:22 [ERROR] Failed to create heartbeat client: UnknownError
14:30:26 [INFO] Heartbeat success!
14:30:27 [INFO] Developer disk image already mounted
14:30:27 [INFO] Auto image mounter has finished, have a great day!
14:30:37 [INFO] Heartbeat success!
14:30:48 [INFO] Heartbeat success!
14:30:58 [INFO] Heartbeat success!
14:31:09 [INFO] Heartbeat success!
14:31:20 [INFO] Heartbeat success!
14:31:24 [INFO] Created PublicStaging directory
14:31:24 [INFO] Created bundle ID directory
14:31:24 [INFO] Sending bytes of ipa
14:31:30 [INFO] Heartbeat success!
14:31:41 [INFO] Heartbeat success!
14:31:47 [ERROR] Unable to install app: ApplicationVerificationFailed
14:34:51 [ERROR] Heartbeat recv failed: MuxError
14:34:51 [INFO] Heartbeat success!
14:35:11 [ERROR] Heartbeat recv failed: MuxError
14:35:11 [INFO] Heartbeat success!
14:35:29 [ERROR] Heartbeat recv failed: MuxError
14:35:29 [INFO] Heartbeat success!
```

I’m connected to wifi and VPN, and I tried by using both my own anisette server and other provided anisette servers (Sideloadly and Sidestore, even switching them between different IPA installs), but the problem still stands.

I did remove app extensions on each install but to no avail.

any help would be appreciated!

### Instructions to reproduce

1. Install IPA from the browse section from Files (removing app extensions)
3. Install a second IPA from the browse section from Files (removing app extensions)
4. “an unknown error occurred”

### What version of SideStore are you using?

0.3.1

**Comment by VIXIVIXIV** [comment] 2023-03-04 15:26
I also have this problem, but it's not a clean install, there are two apps that were installed using 0.1.1 that don't show up as listed in sidestore, and thus I can't reinstall them or refresh the existing install. I also haven't been able to select a pairing file, though

**Comment by crossholo** [comment] 2023-03-04 15:43
> What apps are you trying to install? Seems like a duplicate of another issue.

I tried to install Plex (tweaked), Youtube OLED and BH Twitter. Reversing the order of install doesn’t solve the problem.

**Comment by naturecodevoid** [comment] 2023-03-04 15:49
What are the IPA sizes?

**Comment by VIXIVIXIV** [comment] 2023-03-04 15:51
I'm trying to install uYou+ and Spotilife, uYou is pretty chonky but Spotilife shouldn't be too bad. Installing worked fine on 0.1.1, sidestore can't even self-refresh so it's a lost cause

**Comment by crossholo** [comment] 2023-03-04 16:01
> What are the IPA sizes?

BHTwitter 101.6 MB
Youtube OLED 116.3 MB
PlexTweak 91.5 MB

I don’t know if it’s useful but I used to get some kind of “staging error” on 0.1.1, always when trying to install a second .ipa.

**Comment by naturecodevoid** [comment] 2023-03-05 06:02
0.3.1 has a bug where all errors will show up as an unknown error due to minimuxer changes. You will need to look at minimuxer logs to get the real error. High size IPAs (especially uYou+) are known to cause staging error (ApplicationVerificationFailed), I believe this is a duplicate of that issue.

**Comment by Spidy123222** [comment] 2023-03-07 06:54
Currently highly should have a fix for this.Testing is welcome.

**Comment by naturecodevoid** [comment] 2023-03-07 15:18
Duplicate of staging error issue

**Closed** 2023-03-07 15:18 UTC
Labels: bug
