### ISSUE TITLE
[BUG] Unable to connect to the device error when attempting to refresh

### ISSUE THREAD

**Issue by RaptorWasTaken** [SideStore/SideStore#528] opened 2023-11-13 03:50 UTC
### Describe the bug

Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFi

I have WireGuard VPN on yet I still get this error when trying to refresh 

error log mainly consists of this one error repeated:

thread
22:40:22 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
22:40:29 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError

### Instructions to reproduce

Install using sidesever on macOS Ventura 13.2 onto iPhone 15 running iOS 17

try to refresh an app

### What version of SideStore are you using?

0.5.2

### Other info

Can’t put whole error log due to length

**Comment by nythepegasus** [comment] 2023-11-17 06:37
Hello! Try making a new pairing file with jitterbugpair and ensuring your WiFi and VPN is on.

**Comment by Write** [comment] 2023-11-24 19:34
In the Wiki it says that we don't need to follow the jitterbugpair part for macOS (via AltServer).
It always throws this error when I click "+", Idk what to do ¯\_(ツ)_/¯

**Comment by Spidy123222** [comment] 2024-01-09 05:41
> In the Wiki it says that we don't need to follow the jitterbugpair part for macOS (via AltServer).
> 
> It always throws this error when I click "+", Idk what to do ¯\_(ツ)_/¯ 

It's Via sideserver not altserver on macOS. You need to reset your pairing file and use the new one.

**Comment by Spidy123222** [comment] 2024-01-09 05:42
Also is a duplicate of https://github.com/SideStore/SideStore/issues/519

**Closed** 2024-01-09 05:42 UTC
Labels: bug
