### ISSUE TITLE
[BUG] SideStore claiming a newer version is available when it’s on latest.

### ISSUE THREAD

**Issue by anoraktrend** [SideStore/SideStore#670] opened 2024-08-10 23:35 UTC
### Describe the bug

Updated from 0.5.6 to 0.5.7 and it’s claiming 0.5.6 is still the latest.

### Instructions to reproduce

Update via side loading.

### What version of SideStore are you using?

V0.5.7+

**Comment by yodaluca23** [comment] 2024-08-10 23:46
Duplicate of #666

**Closed** 2024-08-11 00:15 UTC
Labels: bug
