### ISSUE TITLE
[BUG] SideStore showing old update

### ISSUE THREAD

**Issue by Konngitas** [SideStore/SideStore#698] opened 2024-09-14 13:53 UTC
### Describe the bug

Duplicating #666 since that issue was never reopened and the bug is still present
On version 0.5.8, SideStore is still showing an update prompt for old versions of SideStore.

### Instructions to reproduce

Install newest version (0.5.8).
Open My Apps page.

### What version of SideStore are you using?

0.5.8

### Other info
Just opening this issue so attention is brought to it since the other issue was never reopened. Please reopen #666 or use this issue instead.

_No response_

**Comment by jimmysofat6864** [comment] 2024-09-26 01:25
same issue

**Comment by mahee96** [comment] 2024-11-09 09:10
PR #728 fixes this, reopen if the issue is not yet resolved by the nightly build. Thanks

**Closed by mahee96** 2024-11-09 09:10 UTC
Labels: bug
