### ISSUE TITLE
[BUG] sidestore breaks everytime it is refreshed.

### ISSUE THREAD

**Issue by FilipinoRepo** [SideStore/SideStore#715] opened 2024-10-15 12:40 UTC
### Describe the bug

whenever I try and refresh sidestore, it just crashes and refuses to open. this is a really annoying bug since i have had to reinstall sidestore around 15 times last week. if there is any solution to this then I would really appreciate it.

### Instructions to reproduce

just refresh sidestore lol

### What version of SideStore are you using?

0.5.8/0.5.9 nightly

**Comment by Creative-Difficulty** [comment] 2024-10-15 19:54
related to / possible duplicate of #711

**Comment by wangdahua576635956** [comment] 2024-10-17 15:03
The administrator told me“this is a support request and not a bug, please use Discord or GitHub Discussions for support”, And closed the question.

**Comment by wangdahua576635956** [comment] 2024-10-17 15:04
The administrator told me“this is a support request and not a bug, please use Discord or GitHub Discussions for support”, And closed the question

**Closed** 2024-10-17 15:12 UTC
Labels: bug
