### ISSUE TITLE
Unable to connect to the device, make sure Wireguard is enabled and youre connected to WIFI[BUG] 

### ISSUE THREAD

**Issue by Talhaimran03** [SideStore/SideStore#601] opened 2024-04-12 08:22 UTC
### Describe the bug

I'm using iPhone 14 Pro Max with IOS 17.4.1 and SideStore 0.5.4. 
When i try to install an ipa file from sidestore i recieve this error.

### Instructions to reproduce

Even if i reinstall every thing like i did the first time it doesn't work. 
I have: 
- installed altserver, sidestore, wireguard
- paired the device
- enabled the vpn whith the config file
But nothing changes.

### What version of SideStore are you using?

0.5.4

### Other info

I don't know if it has anything to do with it, but when i reinstalled sideserver on my iPhone i recieved this wornig message: 'Installing AltStore with Multiple AltServers Not Supported
Please use the same AltServer you previously used with this Apple ID, or else apps installed with other AltServers will stop working.
Are you sure you want to continue?'

**Comment by hahahaaaaaaaaa** [comment] 2024-04-21 21:12
im having the same exact issue

**Comment by Jonaykon** [comment] 2024-04-22 15:00
i had the same issue, deleting the pairing files in sidestore folder, creating a new pairing file and then reopening sidestore and selection it solved the problem

**Comment by hahahaaaaaaaaa** [comment] 2024-04-22 18:31
what I did is literally spam the refresh button, which didnt work. I reinstalled sidestore multiple times, even deleting it completely. I also tried resetting the pairing file multiple times, also didnt work. But what i didnt try is deleting the pairing file from the folder, which i didnt even think about. I will give it a try and come back with feedback.

**Comment by hahahaaaaaaaaa** [comment] 2024-04-22 18:53
i am back, it did not work unfortunately. I just downloaded it yesterday, and it literally broke within hours. I even tried using my own anisette server to possibly combat this issue, but not luck. However, I have found that using the refresh apps shortcut does work. which is weird. To add to this, if you go to the browse section and click on anything free to install, it will give the same error, but, if you click on the banner of the application, and then after the description and everything with it opens, you can click the "free" button from there, and it will miraculously start installing the app. I am very disappointed to say the very least, I was hoping the days of needing my computer every week to refresh are gone. But here we are, i reinstalled altstore again.

**Comment by Jonaykon** [comment] 2024-04-28 12:39
Refreshing the pairing file does NOT seem to be the solution, I have noticed a pattern that when my computer is on it doesent work, disconnecting from the Internet and turning of Bluetooth on my computer seems to fix the problem (you probably only need to do one them) (turning it off would probably work too)

**Comment by Exe008** [comment] 2024-05-02 11:36
> Refreshing the pairing file does NOT seem to be the solution, I have noticed a pattern that when my computer is on it doesent work, disconnecting from the Internet and turning of Bluetooth on my computer seems to fix the problem (you probably only need to do one them) (turning it off would probably work too)

I can confirm this worked for me as well ...
SideStore first was unable to connect -> tried resetting the pairing file (did not fix it) -> connected with phone to laptop with cable and tried creating new pairing file and resetting with that (did not work) -> turned off laptop wifi (DID WORK) -> turned laptop wifi back on (still works).

Almost as if the laptop wifi "hogs the spot" that the iphone needs in order to refresh. I wonder if other devices could take up the slot as well - like what about a second laptop on the network, heck what about a smart-fridge?!
So far it seems limited to the one laptop I used to sideload it all to begin with though... 🤔

**Comment by jsh722** [comment] 2024-05-02 12:50
try connecting to the vpn after opening the sidestore app. close it from app switcher first.

**Closed** 2024-05-28 13:34 UTC
Labels: bug

**Comment by Talhaimran03** [comment] 2024-05-28 13:36
> Refreshing the pairing file does NOT seem to be the solution, I have noticed a pattern that when my computer is on it doesent work, disconnecting from the Internet and turning of Bluetooth on my computer seems to fix the problem (you probably only need to do one them) (turning it off would probably work too)

I can confirm this worked for me as well

**Comment by Pro-Noobiez** [comment] 2024-08-19 05:00
I also have this problem, tried resetting the pairing file, reinstalling SideStore and spamming buttons. The refresh shortcut doesn’t work. I can install apps but halfway through it says “AFC was unable to manage files on the device” something something…. Guess SideStore is unusable for me now

**Comment by LeoMonkey** [comment] 2025-01-10 14:20
> try connecting to the vpn after opening the sidestore app. close it from app switcher first.

It works for me, seems WireGuard only works after SideStore has been open.

**Comment by michael1900** [comment] 2025-01-10 14:26
> > try connecting to the vpn after opening the sidestore app. close it from app switcher first.
> 
> It works for me, **seems WireGuard only works after SideStore has been open.**

Completely false.
