### ISSUE TITLE
[BUG] Unable to install the app from the staging directory

### ISSUE THREAD

**Issue by lingsoul** [SideStore/SideStore#333] opened 2023-04-03 03:24 UTC
### Describe the bug

The operation couldn’t be completed. Unable to install the app from the staging directory
Version: 0.3.2-nightly.2023.04.02.1

### Instructions to reproduce

SideStore.OperationError error 18
The operation couldn’t be completed. Unable to install the app from the staging directory

### What version of SideStore are you using?

0.3.2-nightly.2023.04.02.1

**Comment by naturecodevoid** [comment] 2023-04-03 14:25
duplicate of staging error

**Closed by naturecodevoid** 2023-04-03 14:25 UTC
Labels: bug
