### ISSUE TITLE
[BUG] YouTube version 18.xx.xx doesn’t install

### ISSUE THREAD

**Issue by binnichtaktiv** [SideStore/SideStore#243] opened 2023-01-28 14:19 UTC
When I try to install YouTube version 17.xx.xx it’s working fine but when I try 18.xx.xx I get unable to install error and this white app icon

I installed SideStore with the sideserver app from sidestore.io and then used the sidestore vpn to sideload 

It has noting to do with the ipa because it’s working fine with other tools like esign, appdb, sideloadly, zsign etc

Here are the ipa files if this helps:
Version 17.48.2 (the ipa that works without problems)
https://hostigram.xyz/?tkn=pYjPNXsfLuMehjMLaMhETeZOehiMGTgKirSGWs4wp98ZP
version 18.02.3 (not working)
https://hostigram.xyz/?tkn=4SwlH3YUZ2HhGhhrBCCrBNAhH1inszpvpZGRoAwrcJbuH

![41FF350F-6BA0-475A-ADBF-6114605D3149](https://user-images.githubusercontent.com/96953964/215271320-a1053748-ecf2-41b3-8942-8a626830d95b.jpeg)
![7870D4BE-C134-43B6-885C-F149AA934081](https://user-images.githubusercontent.com/96953964/215271322-81263900-29f8-4518-8356-0bd623d7c81a.jpeg)

**Comment by naturecodevoid** [comment] 2023-01-30 22:55
Duplicate of #170

**Closed** 2023-01-30 22:55 UTC
Labels: bug

**Comment by binnichtaktiv** [comment] 2023-01-31 09:02
> Duplicate of #170

200mb is apples app size limit?🤔

**Comment by naturecodevoid** [comment] 2023-02-08 15:11
No, it's an issue with SideStore we are trying to fix.

**Comment by eeshankeni** [comment] 2023-10-27 21:11
Weirdly enought, altstore seems to install fine. Theres also this [patching tool which](https://github.com/altstoreio/AltStore/issues/291) lets altstore install large apps.
