### ISSUE TITLE
[BUG] SideStore.OperationError error 4

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#426] opened 2023-07-29 07:31 UTC
### Describe the bug

I get this error message when I try to refresh the apps. It said to open a GitHub issue so that's what I'm doing. I tried refreshing multiple times and made sure wireguard was enabled but I still have the issue. 

The operation couldn’t be completed. An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again. If the issue persists, report it on GitHub Issues!

### Instructions to reproduce

Attempt to install any app or refresh any existing apps and see the issue. 

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment] 2023-07-29 07:47
Duplicate of #423

**Closed by naturecodevoid** 2023-07-29 07:47 UTC
Labels: bug
