### ISSUE TITLE
[BUG] Can't install apps, an unknown error occured.

### ISSUE THREAD

**Issue by KineticAeon** [SideStore/SideStore#284] opened 2023-03-01 23:27 UTC
### Describe the bug

When attempting to install apps in the browse section and while installing directly from a file, the error message "An unknown error occurred." appears. The installed app shows a blank icon on the home screen and gives the message "This app could not be installed because its integrity could not be verified." intead of opening.

### Instructions to reproduce

1. Use default SideStore server.
2. Sign in with your Apple ID.
3. Attempt to install an app.

### What version of SideStore are you using?

0.3.1

### Other info

![E88452AF-CFF8-4B1B-B2DA-073D1FAF3A21](https://user-images.githubusercontent.com/56273352/222289908-8d7d3c50-c11a-4338-bd90-3ccf37ea7058.jpeg)
![77C795E6-1190-41CE-B4E6-BCB049BDDFF2](https://user-images.githubusercontent.com/56273352/222289918-def686bf-b89c-4798-b659-881c08f05b7e.png)

**Comment by KineticAeon** [comment] 2023-03-01 23:32
I realize some logs may be helpful here, so I've got the output I get here:
```

23:15:48 [INFO] Logger initialized!!
23:15:48 [INFO] Starting heartbeat thread
23:15:53 [ERROR] Failed to create heartbeat client: UnknownError
23:15:53 [INFO] Developer disk image already mounted
23:15:53 [INFO] Auto image mounter has finished, have a great day!
23:15:53 [INFO] Heartbeat success!
23:16:04 [INFO] Heartbeat success!
23:16:14 [INFO] Heartbeat success!
23:16:25 [INFO] Heartbeat success!
23:16:34 [INFO] Created PublicStaging directory
23:16:34 [INFO] Created bundle ID directory
23:16:34 [INFO] Sending bytes of ipa
23:16:36 [INFO] Heartbeat success!
23:16:45 [ERROR] Unable to install app: ApplicationVerificationFailed
23:16:46 [INFO] Heartbeat success!
23:20:37 [ERROR] Heartbeat recv failed: MuxError
23:20:38 [INFO] Heartbeat success!
23:24:19 [ERROR] Heartbeat recv failed: MuxError
23:24:56 [ERROR] Failed to create heartbeat client: UnknownError
23:24:56 [INFO] Heartbeat success!
23:25:07 [INFO] Heartbeat success!
23:25:14 [INFO] Minimuxer finished installing profile!!
23:25:14 [INFO] Minimuxer finished installing profile!!
23:25:18 [INFO] Heartbeat success!
23:25:28 [INFO] Heartbeat success!
23:25:39 [INFO] Heartbeat success!
23:25:50 [INFO] Heartbeat success!
23:26:00 [INFO] Heartbeat success!
23:26:11 [INFO] Heartbeat success!
23:26:21 [INFO] Heartbeat success!
23:26:31 [INFO] Heartbeat success!
23:26:34 [INFO] Created PublicStaging directory
23:26:34 [INFO] Created bundle ID directory
23:26:34 [INFO] Sending bytes of ipa
23:26:42 [INFO] Heartbeat success!
23:26:51 [ERROR] Unable to install app: ApplicationVerificationFailed
23:26:53 [INFO] Heartbeat success!
23:28:54 [ERROR] Heartbeat recv failed: MuxError
23:28:56 [INFO] Heartbeat success!
23:29:07 [INFO] Heartbeat success!
23:29:17 [INFO] Heartbeat success!
23:29:28 [INFO] Heartbeat success!
23:29:39 [INFO] Heartbeat success!
23:29:49 [INFO] Heartbeat success!
23:30:00 [INFO] Heartbeat success!
23:30:11 [INFO] Heartbeat success!
23:30:35 [ERROR] Heartbeat recv failed: MuxError
23:30:35 [INFO] Heartbeat success!
23:30:46 [INFO] Heartbeat success!

```

**Comment by KineticAeon** [comment] 2023-03-02 13:53
Switching to my own hosted anisette server solved the problem.

**Comment by lingsoul** [comment] 2023-03-03 02:40
> Switching to my own hosted anisette server solved the problem.

I tried it. It doesn't seem to work for me. It's the same error

**Comment by naturecodevoid** [comment] 2023-03-03 05:38
Are you on 16.4 beta? Could you send minimuxer logs (and also app logs, if you have a computer with libimobiledevice installed)?

**Comment by KineticAeon** [comment] 2023-03-04 23:53
I can no longer install apps. I was able to renew two of the apps but no new ones can be installed and give the same error. Tried with both the browse tab and an IPA.

Minimuxer logs:
```
23:32:49 [INFO] Logger initialized!!
23:32:49 [INFO] Starting heartbeat thread
23:32:51 [INFO] Heartbeat success!
23:32:54 [INFO] Developer disk image already mounted
23:32:54 [INFO] Auto image mounter has finished, have a great day!
23:33:02 [INFO] Heartbeat success!
23:33:13 [INFO] Heartbeat success!
23:33:23 [INFO] Heartbeat success!
23:33:34 [INFO] Heartbeat success!
23:33:44 [INFO] Heartbeat success!
23:33:55 [INFO] Heartbeat success!
23:34:30 [ERROR] Heartbeat recv failed: MuxError
23:34:30 [INFO] Heartbeat success!
23:34:41 [INFO] Heartbeat success!
23:36:54 [ERROR] Heartbeat recv failed: MuxError
23:36:54 [WARN] Could not get device from muxer for heartbeat
23:36:54 [WARN] Could not get device from muxer for heartbeat
23:36:55 [WARN] Could not get device from muxer for heartbeat
23:36:55 [WARN] minimuxer is rebinding to the muxer socket!!
23:36:55 [INFO] minimuxer has bound successfully
23:36:56 [INFO] Heartbeat success!
23:37:07 [INFO] Heartbeat success!
23:37:17 [INFO] Heartbeat success!
23:37:28 [INFO] Heartbeat success!
23:37:38 [INFO] Heartbeat success!
23:37:49 [INFO] Heartbeat success!
23:39:17 [ERROR] Heartbeat recv failed: MuxError
23:39:18 [INFO] Heartbeat success!
23:39:28 [INFO] Heartbeat success!
23:39:39 [INFO] Heartbeat success!
23:39:50 [INFO] Heartbeat success!
23:40:00 [INFO] Heartbeat success!
23:40:23 [ERROR] Heartbeat recv failed: MuxError
23:40:23 [INFO] Heartbeat success!
23:40:34 [INFO] Heartbeat success!
23:40:44 [INFO] Heartbeat success!
23:40:55 [INFO] Heartbeat success!
23:40:59 [INFO] Minimuxer finished installing profile!!
23:41:00 [INFO] Minimuxer finished installing profile!!
23:41:00 [INFO] Minimuxer finished installing profile!!
23:41:06 [INFO] Heartbeat success!
23:41:16 [INFO] Heartbeat success!
23:41:27 [INFO] Heartbeat success!
23:41:37 [INFO] Heartbeat success!
23:41:48 [INFO] Heartbeat success!
23:41:58 [INFO] Heartbeat success!
23:42:01 [INFO] Created PublicStaging directory
23:42:01 [INFO] Created bundle ID directory
23:42:01 [INFO] Sending bytes of ipa
23:42:08 [INFO] Heartbeat success!
23:42:19 [INFO] Heartbeat success!
23:42:20 [ERROR] Unable to install app: ApplicationVerificationFailed
23:42:30 [INFO] Heartbeat success!
23:42:40 [INFO] Heartbeat success!
23:42:51 [INFO] Heartbeat success!
23:43:01 [INFO] Created PublicStaging directory
23:43:01 [INFO] Created bundle ID directory
23:43:01 [INFO] Sending bytes of ipa
23:43:02 [INFO] Heartbeat success!
23:43:06 [ERROR] Unable to install app: UnknownError
23:43:12 [INFO] Heartbeat success!
23:43:23 [INFO] Heartbeat success!
23:43:33 [INFO] Heartbeat success!
23:43:44 [INFO] Heartbeat success!
23:43:55 [INFO] Heartbeat success!
23:44:05 [INFO] Heartbeat success!
23:44:16 [INFO] Heartbeat success!
23:44:27 [INFO] Heartbeat success!
23:44:37 [INFO] Heartbeat success!
23:44:48 [INFO] Heartbeat success!
23:44:58 [INFO] Heartbeat success!
23:45:08 [INFO] Heartbeat success!
23:45:19 [INFO] Heartbeat success!
23:45:29 [INFO] Heartbeat success!
23:47:22 [ERROR] Heartbeat recv failed: MuxError
23:47:27 [ERROR] Failed to create heartbeat client: UnknownError
23:47:28 [INFO] Heartbeat success!
23:48:41 [ERROR] Heartbeat recv failed: MuxError
23:48:41 [INFO] Heartbeat success!
23:48:51 [INFO] Heartbeat success!
23:49:02 [INFO] Heartbeat success!
23:49:13 [INFO] Heartbeat success!
23:49:23 [INFO] Heartbeat success!
23:49:34 [INFO] Heartbeat success!
23:49:45 [INFO] Heartbeat success!
23:49:55 [INFO] Heartbeat success!
23:50:06 [INFO] Heartbeat success!
23:50:16 [INFO] Heartbeat success!
23:50:26 [INFO] Heartbeat success!
23:50:28 [INFO] Created PublicStaging directory
23:50:28 [INFO] Created bundle ID directory
23:50:28 [INFO] Sending bytes of ipa
23:50:37 [ERROR] Unable to install app: ApplicationVerificationFailed
23:50:37 [INFO] Heartbeat success!
23:51:41 [ERROR] Heartbeat recv failed: MuxError
23:51:41 [INFO] Heartbeat success!
```

**Comment by naturecodevoid** [comment] 2023-03-05 06:09
What apps are you trying to install? Larger apps (especially uYou+) tend to cause staging error (ApplicationVerificationFailed). This is a known issue. 0.3.1 has a bug where all errors will show up as unknown error, due to a recent minimuxer change.

**Comment by KineticAeon** [comment] 2023-03-05 17:07
I've been trying Enmity. What counts as a larger app in terms of file size? The IPAs I've been using don't seem to ever get close to a GB. Deltroid doesn't install either though, so I'm not sure it's the same issue.

**Comment by KineticAeon** [comment] 2023-03-05 17:26
I'm not sure if these will help, but I'm now getting different errors from the sources tab. The last two errors (PackageInspectionFailed for uYou+ and ObjectNotFound for Deltroid) are new.
```
17:08:20 [INFO] Logger initialized!!
17:08:20 [INFO] Starting heartbeat thread
17:08:23 [INFO] Heartbeat success!
17:08:26 [INFO] Successfully uploaded the image
17:08:27 [INFO] Successfully mounted the image
17:08:27 [INFO] Auto image mounter has finished, have a great day!
17:08:34 [INFO] Heartbeat success!
17:08:44 [INFO] Heartbeat success!
17:08:55 [INFO] Heartbeat success!
17:09:06 [INFO] Heartbeat success!
17:09:16 [INFO] Heartbeat success!
17:09:27 [INFO] Heartbeat success!
17:09:38 [INFO] Heartbeat success!
17:09:48 [INFO] Heartbeat success!
17:09:59 [INFO] Heartbeat success!
17:10:05 [INFO] Created PublicStaging directory
17:10:05 [INFO] Created bundle ID directory
17:10:05 [INFO] Sending bytes of ipa
17:10:09 [INFO] Heartbeat success!
17:10:20 [INFO] Heartbeat success!
17:10:31 [INFO] Heartbeat success!
17:10:36 [ERROR] Unable to install app: ApplicationVerificationFailed
17:10:41 [INFO] Heartbeat success!
17:12:52 [ERROR] Heartbeat recv failed: MuxError
17:12:57 [INFO] Heartbeat success!
17:13:07 [INFO] Heartbeat success!
17:16:11 [ERROR] Heartbeat recv failed: MuxError
17:16:13 [INFO] Heartbeat success!
17:16:24 [INFO] Heartbeat success!
17:16:34 [INFO] Heartbeat success!
17:16:45 [INFO] Heartbeat success!
17:16:56 [INFO] Heartbeat success!
17:17:06 [INFO] Heartbeat success!
17:17:17 [INFO] Heartbeat success!
17:17:27 [INFO] Heartbeat success!
17:17:38 [INFO] Heartbeat success!
17:17:49 [INFO] Heartbeat success!
17:17:59 [INFO] Heartbeat success!
17:18:10 [INFO] Heartbeat success!
17:18:21 [INFO] Heartbeat success!
17:18:31 [INFO] Heartbeat success!
17:18:42 [INFO] Heartbeat success!
17:18:53 [INFO] Heartbeat success!
17:18:59 [INFO] Created PublicStaging directory
17:18:59 [INFO] Created bundle ID directory
17:18:59 [INFO] Sending bytes of ipa
17:19:03 [INFO] Heartbeat success!
17:19:14 [INFO] Heartbeat success!
17:19:25 [INFO] Heartbeat success!
17:19:35 [INFO] Heartbeat success!
17:19:38 [ERROR] Unable to install app: PackageInspectionFailed
17:19:46 [INFO] Heartbeat success!
17:20:15 [ERROR] Heartbeat recv failed: MuxError
17:20:15 [INFO] Heartbeat success!
17:20:25 [INFO] Heartbeat success!
17:20:38 [ERROR] Heartbeat recv failed: MuxError
17:20:38 [INFO] Heartbeat success!
17:20:48 [INFO] Heartbeat success!
17:20:59 [INFO] Heartbeat success!
17:21:09 [INFO] Heartbeat success!
17:21:20 [INFO] Heartbeat success!
17:21:31 [INFO] Heartbeat success!
17:21:41 [INFO] Heartbeat success!
17:21:42 [INFO] Created PublicStaging directory
17:21:42 [ERROR] Unable to read bundle ID info: ObjectNotFound
17:21:52 [INFO] Heartbeat success!
17:22:03 [INFO] Heartbeat success!
17:22:13 [INFO] Heartbeat success!
17:22:24 [INFO] Heartbeat success!
17:23:18 [ERROR] Heartbeat recv failed: MuxError
17:23:18 [INFO] Heartbeat success!
```

**Comment by naturecodevoid** [comment] 2023-03-05 17:56
IPAs that are 100MB+ most commonly get staging error.

**Comment by KineticAeon** [comment] 2023-03-06 04:00
Thank you.

**Comment by ramic12** [comment] 2023-03-11 01:05
Im downloading 1 mb app and its still saying an unknown error occured

**Comment by naturecodevoid** [comment] 2023-03-11 21:11
duplicate of staging error

**Closed** 2023-03-11 21:11 UTC
Labels: bug

**Comment by naturecodevoid** [comment] 2023-03-11 23:33
> Im downloading 1 mb app and its still saying an unknown error occured

could you send minimuxer logs?

**Comment by bao3** [comment] 2023-03-12 05:57
same issue ~~~
