### ISSUE TITLE
[BUG] sidestore crashing after successfully refreshed an app

### ISSUE THREAD

**Issue by ryanhuang10** [SideStore/SideStore#420] opened 2023-07-27 20:59 UTC
### Describe the bug

SideStore actually crashes after refreshing an app successfully

### Instructions to reproduce

Maybe update sidestore to a much newer version

### What version of SideStore are you using?

0.5.0

**Comment by naturecodevoid** [comment] 2023-07-27 21:14
Can you send the crash report?

Go into settings > privacy > analytics & improvements > analytics data and search (scroll up) for SideStore, then choose the one with the most recent date and send it here or to @naturecodevoid on Discord

**Comment by ryanhuang10** [comment] 2023-07-28 20:48
What is the report name

**Comment by naturecodevoid** [comment] 2023-07-28 21:04
It should just be SideStore, as I said in the first message, just search for SideStore and send the most recent one

**Comment by ryanhuang10** [comment] 2023-07-28 21:12
I see everything with sidestore at the beginning of the name but can’t find that has only word sidestore in it

**Comment by naturecodevoid** [comment] 2023-07-28 23:00
Just choose the most recent one with SideStore in the name

**Comment by jimmysofat6864** [comment] 2023-07-29 07:42
Mine does a similar thing and I have the logs and a video attached here. 

https://github.com/SideStore/SideStore/assets/69532417/bae69a5d-8275-4069-ae0b-bceed70382e5

**Comment by naturecodevoid** [comment] 2023-07-29 07:51
This issue is most likely caused by libplist, libplist has been known to crash for some apps. Ny has also gotten this crash and confirmed it as libplist. It may be caused by a possible memory leak in plist_plus identified by a team member, but if it isn't, you'll either have to wait for rsmobiledevice or refresh your apps one by one and do the one that crashes last.

**Comment by xhfpsxm** [comment] 2023-07-31 02:17
> Mine does a similar thing and I have the logs sent via discord and a video attached here on what mine does.
> 
>  RPReplay_Final1690616480.MP4


I'm in the same situation. Same error, same tweaks.

**Comment by abhishekgi** [comment] 2023-08-04 09:23
Just remove the sidestore widget from Home Screen and this issue will be fixed

**Comment by xhfpsxm** [comment] 2023-08-04 10:11
> Just remove the sidestore widget from Home Screen and this issue will be fixed

Thank you. I fixed the problem with your advice. I'm sorry that I can't use the widget, but I hope this will improve in the future.

**Comment by abhishekgi** [comment] 2023-08-04 13:39
Great !
Change issue name to “ sidestore craching on Home Screen if these is aSidestore widget “.

**Comment by ajarang** [comment] 2023-08-24 01:07
Not sure if I have similar issues, but I don't have the widget on my home screen and I am getting the same issues. I've attatched my error log. 
[AltStore-2023-08-18-080846.zip](https://github.com/SideStore/SideStore/files/12424422/AltStore-2023-08-18-080846.zip)

**Comment by ajarang** [comment] 2023-08-25 12:26
i uninstalled altstore before i installed sidestore, then reinstalled my existing sideloaded apps so that those apps were "tied" to sidestore. Should I have done something else?

**Comment by abhishekgi** [comment] 2023-08-25 13:11
> i uninstalled altstore before i installed sidestore, then reinstalled my existing sideloaded apps so that those apps were "tied" to sidestore. Should I have done something else?

You should use altserver(not sideserver) for installing sidestore, after that it should work

**Comment by ajarang** [comment] 2023-08-25 15:04
will try installing with altserver. The website says to use sideserver, so thats what I used. 

Also realized that I accidentally uploaded altstore logs instead of sidestore. I've attached the correct logs to my comment above.

**Comment by junepark678** [comment] 2024-08-16 09:07
stale

**Closed by junepark678** 2024-08-16 09:07 UTC
Labels: bug
