### ISSUE TITLE
[FEATURE REQUEST] An auto enable JIT feature

### ISSUE THREAD

**Issue by Creeper76** [SideStore/SideStore#395] opened 2023-06-20 23:35 UTC
### Describe the feature

I think it would be cool if you could make it so that when you open an app, like dolphin emulator, auto enabled JIT.

### Use cases

Emulators that require JIT

### Alternatives

It could be like the refresh all apps shortcut but for enabling JIT

**Comment by naturecodevoid** [comment] 2023-06-20 23:36
This will be possible when SideKit is ready but will require developers to use (probably, it may be compatible with AltKit)

**Comment by Spidy123222** [comment] 2023-06-20 23:38
Duplicate of https://github.com/SideStore/SideStore/issues/166

**Closed** 2023-06-20 23:38 UTC
Labels: enhancement
