### ISSUE TITLE
[BUG] Deactivating app causing "Unable to install the app from the staging directory"

### ISSUE THREAD

**Issue by dlfnn** [SideStore/SideStore#369] opened 2023-05-30 04:03 UTC
### Describe the bug

Deactivating app fails with "The operation couldn’t be completed. Unable to install the app from the staging directory", minimuxer.MinimuxerError error 16. Happens for SpotC++ and UYouPlus, might also be the case for other apps.

### Instructions to reproduce

While in the "My Apps" tab in sidestore, hold tap on installed app and select "Deactivate"

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment] 2023-05-30 04:03
duplicate of staging error issue

**Closed by naturecodevoid** 2023-05-30 04:03 UTC
Labels: bug

**Comment by dlfnn** [comment] 2023-05-30 04:05
It is not due to the 3 apps limit given I was attempting to deactivate apps.

**Comment by dlfnn** [comment] 2023-05-30 04:29
Sorry to bother, but is there currently a fix to this? I've scanned through the issues and there doesn't seems to be similar situations when *deactivating* an app cause this problem

**Comment by dlfnn** [comment] 2023-05-30 04:38
seems to be #299

**Comment by naturecodevoid** [comment] 2023-05-30 19:16
Deactivating is known to cause issues, we plan to fix it by 1.0
