### ISSUE TITLE
[BUG] Unable to connect to device~

### ISSUE THREAD

**Issue by xhfpsxm** [SideStore/SideStore#561] opened 2023-12-22 22:03 UTC
### Describe the bug

https://github.com/SideStore/SideStore/assets/60850613/8f94d82b-1002-4519-a16a-0392d7d4294d

This error occurred in 0.5.2.

And I updated to 0.5.4.

But it has still not been resolved.

Someone said this was a duplicated issue.

I installed using alt-server and

I also recreated the pairing file.

And I reinstalled many times.

I searched for a solution to this but failed.

iOS version is 17.0.

I don't know if has something to do with this.

Please tell me what to do.

### Instructions to reproduce

Install sidestore 0.5.2 or 0.5.4

Login

Connect to vpn

Refresh or press the +button.

### What version of SideStore are you using?

0.5.4

**Comment by Zaciscool** [comment] 2023-12-22 22:11
If you are on iOS 17.0 you can use troll store it has no app limits and no need to refresh yourself

**Comment by xhfpsxm** [comment] 2023-12-22 23:03
> If you are on iOS 17.0 you can use troll store it has no app limits and no need to refresh yourself

I am waiting for trollstore 2. That's why I didn't update from 17.0. My iPhone is xs max and I know it needs more time to install on the xs max.

**Comment by Zaciscool** [comment] 2023-12-22 23:08
> > If you are on iOS 17.0 you can use troll store it has no app limits and no need to refresh yourself
> 
> I am waiting for trollstore 2. That's why I didn't update from 17.0. My iPhone is xs max and I know it needs more time to install on the xs max.

Isn’t trollstore 2 out? Wdym by more time

**Comment by xhfpsxm** [comment] 2023-12-22 23:16
> Isn’t trollstore 2 out? Wdym by more time

I know that it can only be installed on iPhones with a8 to a11 chip.

**Comment by kibology** [comment] 2023-12-25 19:30
I was also experiencing  this issue on iOS 17.0 (iPhone 13), turning on Wireguard and leaving the app open for 30~ seconds before trying to refresh worked in my case.

**Comment by xhfpsxm** [comment] 2023-12-25 19:40
> I was also experiencing this issue on iOS 17.0 (iPhone 13), turning on Wireguard and leaving the app open for 30~ seconds before trying to refresh worked in my case.

Did you solve the problem by leaving it open for 30 seconds?

**Comment by kibology** [comment] 2023-12-25 19:54
Just tried it again and yeah it takes about 20 seconds before the message stops popping up and my apps refresh. I'm on 0.54 nightly

**Comment by kibology** [comment] 2023-12-25 19:55
I'd try using the nightly build if you keep having problems as I was experiencing the same issue on the stable release

**Comment by kibology** [comment] 2023-12-25 20:06
I'd also like to add, I was having a ton of issues getting sidestore to work but I found a workaround on Reddit, not sure if it really did anything or not but I haven't had any issues since. 

1. Install the Altstore IPA using the Altserver

2. Install Sidestore IPA with the installed Altstore IPA 

3. Go through the Sidestore setup, disable wireguard and delete Altstore 

4. Re-enable wireguard and try installing an app.

**Comment by xhfpsxm** [comment] 2023-12-25 22:32
> I'd also like to add, I was having a ton of issues getting sidestore to work but I found a workaround on Reddit, not sure if it really did anything or not but I haven't had any issues since.
> 
> 1. Install the Altstore IPA using Altserver
> 2. Install Sidestore IPA with the installed Altstore IPA
> 3. Go through the Sidestore setup, disable wireguard and delete Altstore
> 4. Re-enable wireguard and try installing an app.

Thank you for your answer. I'll give it a try.

**Comment by Spidy123222** [comment] 2024-01-09 05:43
This is currently a duplicate of https://github.com/SideStore/SideStore/issues/519

**Comment by Spidy123222** [comment] 2024-01-09 05:43
> I'd also like to add, I was having a ton of issues getting sidestore to work but I found a workaround on Reddit, not sure if it really did anything or not but I haven't had any issues since. 
> 
> 1. Install the Altstore IPA using Altserver
> 
> 2. Install Sidestore IPA with the installed Altstore IPA 
> 
> 3. Go through the Sidestore setup, disable wireguard and delete Altstore 
> 
> 4. Re-enable wireguard and try installing an app.
> 

Just use altserver to install sidestore using sideload ipa. It's just the same thing.

**Closed** 2024-01-09 05:44 UTC
Labels: bug
