### ISSUE TITLE
[BUG] Unable to install any other IPA after one IPA installation on 0.4.0 SideStore

### ISSUE THREAD

**Issue by mayank3183** [SideStore/SideStore#406] opened 2023-07-08 03:48 UTC
### Describe the bug

I was able to load one app successfully using SideStore. However when I try to load any other second app I always get error "The operation couldn't be completed. Unable to install the app from the staging directory". In the SideStore error logs I can see following error, "minimuxer.MiniuxerError error 16". I tried 2 different apps which were perfectly working with AltStore but they give this error with SideStore.

I am using following versions:
SideStore:  0.4.0
IOS:           15.7.4
WireGuard: 1.0.16(27)

### Instructions to reproduce

Once SideStore is installed, add any first app and that should work.
Now try to install any other app from IPA and all will give the error
"The operation couldn't be completed. Unable to install the app from the staging directory", "minimuxer.MiniuxerError error 16"
I am using following versions:
SideStore:  0.4.0
IOS:           15.7.4
WireGuard: 1.0.16(27)

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment] 2023-07-08 13:47
Duplicate of staging error

**Closed by naturecodevoid** 2023-07-08 13:48 UTC
Labels: bug

**Comment by mayank3183** [comment] 2023-07-08 19:00
Could tou tell me is there workaround or I cannot load any second app due to this issue.
Not clear as tou closed it saying duplicate and not planned

**Comment by naturecodevoid** [comment] 2023-07-09 14:14
Closing the issue as "not planned" can also mean "won't fix, can't repro, duplicate, stale" according to GitHub
