### ISSUE TITLE
[BUG] SideStore not loading

### ISSUE THREAD

**Issue by loopdee43** [SideStore/SideStore#358] opened 2023-05-02 01:44 UTC
### Describe the bug

It was working earlier, but now whenever I open SideStore it hangs on a grey screen, and then eventually crashes. I don't know what caused it, therefore I don't know how one could reproduce it. I'm using the test build from the discord [PR311](https://cdn.discordapp.com/attachments/1037581733144559676/1088318838380187688/SideStorePR311.ipa)

(I can't view the version so I just put PR311)

### Instructions to reproduce

(This is how it happened for me, twice, once with the test build and once with the latest build) 
1.) Sideload SideStore w/ AltServer (latest)
2.) Download something from SideStore (and use the application)
3.) Re-enter SideStore and click refresh
4.) Close out of SideStore and do something else. This is where it stopped working for me, restarting my phone (13 Pro) does not solve the issue. 

### What version of SideStore are you using?

PR311

**Comment by Spidy123222** [comment] 2023-05-02 01:55
Duplicate of https://github.com/SideStore/SideStore/issues/356

**Closed** 2023-05-02 01:55 UTC
Labels: bug

**Comment by loopdee43** [comment] 2023-05-02 02:02
That's the same problem as this? 

https://user-images.githubusercontent.com/90978974/235563779-542f5f99-e8b1-4a83-b732-9a8e449c48ec.MOV

**Comment by loopdee43** [comment] 2023-05-02 02:03
@Spidy123222  Is that the same issue as this?

https://user-images.githubusercontent.com/90978974/235563929-e2244303-910a-47ba-b081-73e630616bb9.MOV

**Comment by Spidy123222** [comment] 2023-05-02 02:12
How you described it sounded like expire early issue but what your showing is different. Go into files and remove the sidestore.log that temporarily fixes the issues but that pr has been closed for other things.

**Comment by loopdee43** [comment] 2023-05-02 02:15
Ah okay sorry for the confusion. That fixed it.
