### ISSUE TITLE
SideStore won’t refresh with uyou +

### ISSUE THREAD

**Issue by matx33** [SideStore/SideStore#438] opened 2023-08-06 09:34 UTC
### Describe the bug

Every app can refresh properly but sidestore when i have uyou+ sideloaded. When i deactivate uyou+ i can refresh sidestore. 
When trying to refresh either the app crashes or i get the message unable to install from staging directory.

### Instructions to reproduce

sideload uyou+ and refresh sidestore

### What version of SideStore are you using?

0.5

**Comment by vmavromatis** [comment] 2023-08-06 15:03
Try reinstalling uyouplus

**Comment by naturecodevoid** [comment] 2023-08-06 17:19
Duplicate of staging error

**Closed by naturecodevoid** 2023-08-06 17:19 UTC
Labels: bug
