### ISSUE TITLE
[BUG] The operation couldn’t be completed. An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.).

### ISSUE THREAD

**Issue by stelick1** [SideStore/SideStore#432] opened 2023-08-01 06:02 UTC
### Describe the bug

it happened for me for the first time, it just keep saying this every time i want to refresh any apps, jit works btw

### Instructions to reproduce

1.go to turkey
2.open sidestore
3.try to refresh app
4.it loading 
5.error

### What version of SideStore are you using?

0.4.0

### Other info

idk

**Comment by naturecodevoid** [comment] 2023-08-01 07:57
Duplicate of #423

**Closed** 2023-08-01 07:57 UTC
Labels: bug
