### ISSUE TITLE
[BUG] Duplicate provisioning profiles causes SideStore to expire randomly

### ISSUE THREAD

**Issue by yur1xpp** [SideStore/SideStore#249] opened 2023-02-04 08:27 UTC
**Describe the bug**
Refreshed all apps at once, including SideStore, but SideStore seems to expire earlier  (`SideStore No Longer Available`) than all other apps. Other apps launched just fine. Reproducible with every latest build in Actions.

**To Reproduce**
1. Refresh all apps
2. Wait few days (4-5 days if not mistaken)
3. SideStore expire

**Expected behavior**
Expire on time, rather than early.

**iDevice (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.1.2-16.3

**Comment by naturecodevoid** [comment] 2023-02-05 00:49
Known issue; not sure if there's an issue for it. A fix is in progress

**Comment by yur1xpp** [comment] 2023-02-12 13:39
Is there any build on the Actions that you know have this fix? It's quite a critical big I would say since this bug defeats the purpose of SideStore altogether. It already hit me countless times that it seems AltStore might seems a better solution after all at the moment.

**Comment by Kayada97** [comment] 2023-02-12 15:26
Use profile_cleanser.py script from pinned in discord

**Comment by naturecodevoid** [comment] 2023-02-12 21:22
I made a fix multiple days ago, but I have not been able to test it since my Xcode was refusing to recognize minimuxer changes so it hasn’t been added to SideStore yet. Profile cleaner might improve things, but it doesn’t help with SideStore using the wrong profile.

**Comment by yur1xpp** [comment] 2023-02-13 12:32
@naturecodevoid I'm gonna try the build in the referenced PR!

**Comment by naturecodevoid** [comment] 2023-02-13 15:34
There are some other testers who have tried it, and while there was an issue at first, it seems to have been resolved. I've been doing a lot of testing and I can no longer reproduce the bug or issues with the fix, and it seems to be stable. Please tell me if it fixes it! If you have a computer and libimobiledevice installed, the output of the command `ideviceprovision list` before and after refreshing would be very helpful to know if it truly works.

**Comment by yur1xpp** [comment] 2023-02-13 16:33
Actually the bug just happens again for me with the PR build, and now it’s only just few hours! (I sideloaded them right after the previous comment)

**Comment by naturecodevoid** [comment] 2023-02-13 20:38
Hm, I'll look into it. Thanks for reporting it 👍

**Comment by velaar** [comment] 2023-02-17 23:22
> 

For me it happens instantly after re-signing SideStore with  SideStore on the latest PR build. Clean install on 2 devices

**Comment by naturecodevoid** [comment] 2023-02-19 04:48
I've had the following scenarios reported:
- Working perfectly (I can reproduce)
- Expires after a few hours (I can reproduce)
- Expires instantly (Haven't been able to reproduce)
Thanks for confirming the instant expire. I thought it was related to upgrading from a previous build, thanks for trying a clean install.

**Comment by Paris0-0** [comment] 2023-03-09 09:57
have the same issue, 0.3.1, sidestore expired again, but other apps can open correctly

**Comment by wangrui1573** [comment] 2023-03-10 00:25
**but SideStore seems to expire earlier (SideStore No Longer Available) than all other apps**

The same question with me

**Comment by naturecodevoid** [comment] 2023-03-10 02:05
This issue is one the biggest issues blocking us from a stable release. There have been many team members investigating this over the past week, and we already noticed that it seems to only happen with SideStore.

**Comment by Paris0-0** [comment] 2023-03-10 02:20
yes, it only happens with SideStore

**Comment by wangrui1573** [comment] 2023-03-10 02:26
yes, it only happens with SideStore，
I noticed that the sidestore also has an altwidget certificate. Does the altwidget expire and cause the sidestore APP to become unavailable?

**Comment by naturecodevoid** [comment] 2023-03-10 03:37
I don't believe so.

**Comment by Paris0-0** [comment] 2023-03-12 07:20
After SideStore is no longer available, it can't be opened from the home screen, but if you haven't killed SideStore's background, you can still open it from the multitasking interface and refresh apps including SideStore correctly. However after refreshing, SideStore still can't open from the home screen

**Comment by naturecodevoid** [comment] 2023-03-12 07:27
Opening from app switcher is a known workaround. however, was that using the PR build or with 0.3.1/nightly?

**Comment by Paris0-0** [comment] 2023-03-12 07:38
> Opening from app switcher is a known workaround. however, was that using the PR build or with 0.3.1/nightly?
> 从应用程序切换器打开是一种已知的解决方法。但是，是使用 PR 版本还是使用 0.3.1/nightly？

0.3.1 downloaded from the release page and purely install.

**Comment by Paris0-0** [comment] 2023-03-16 15:36
It seems that SideStore itself will not be really renewed. After the real renewal, the desktop icon will display the installation animation and the application list in SideStore will be emptied. Rarely refreshing will really refresh SideStore itself. The symbol of real renewal I think is above. Most of the time, even if it is displayed for 7 days, it is still not available. Today, try to enter SideStore from the multitasking interface after expiration and then reinstall SideStore ipa from file, SideStore works again. It's just that the application list is still missing and all apps need to be reinstalled by "+" button

**Comment by naturecodevoid** [comment] 2023-03-16 21:56
first refresh is actually a reinstall, not sure if it's intended

I don't think we want to solve this by reinstalling each refresh since that will make refreshes much longer and probably delete SideStore app data

**Comment by velaar** [comment] 2023-05-27 15:27
I had to move back to AltStore for the time being because of this issue. I wonder if there was further development on it so I can test and hopefully come back to SS. I wish there was more I could to to help.

**Comment by Spidy123222** [comment] 2023-05-27 16:21
> I had to move back to AltStore for the time being because of this issue. I wonder if there was further development on it so I can test and hopefully come back to SS. I wish there was more I could to to help. 

I forgot to close this issue but we solved it on our recent updates to nightly. It requires a fresh install (removed app and installing latest nightly).

**Closed by Spidy123222** 2023-05-27 16:21 UTC
Labels: bug
