### ISSUE TITLE
I encountered the same issue even when I used Windows and a USB cable. Sometimes I can succeed, but most of the time I failed with the captioned issue.

### ISSUE THREAD

**Issue by qhgary** [SideStore/SideStore#238] opened 2023-01-23 15:02 UTC
I encountered the same issue even when I used Windows and a USB cable. Sometimes I can succeed, but most of the time I failed with the captioned issue.

_Originally posted by @qhgary in https://github.com/SideStore/SideStore/issues/158#issuecomment-1400410380_

**Comment by naturecodevoid** [comment] 2023-01-24 05:00
Unable to install app from staging directory is a known issue. If you are having another issue, please re-open this issue. Duplicate of https://github.com/SideStore/SideStore/issues/170

**Closed by naturecodevoid** 2023-01-24 05:00 UTC
