### ISSUE TITLE
Sidestore crashing when trying to install a big ipa (890mb) [BUG] 

### ISSUE THREAD

**Issue by Alexis2009code** [SideStore/SideStore#621] opened 2024-05-10 17:27 UTC
### Describe the bug

When i try to install a ipa of 890mb the app crashes

### Instructions to reproduce

Open sidestore
select a big ipa
wait a little bit
Crash

### What version of SideStore are you using?

last version

**Comment by junepark678** [comment] 2024-08-16 08:58
duplicate of #545

**Closed by junepark678** 2024-08-16 08:58 UTC
Labels: bug
