### ISSUE TITLE
[BUG] “minimuxer.MinimuxerError 16 The operation couldn’t be completed. AFC was unable to manage files on the device“

### ISSUE THREAD

**Issue by Pro-Noobiez** [SideStore/SideStore#679] opened 2024-08-19 05:08 UTC
### Describe the bug

I had installed sidestore on my iPad Air 4th Generation, iPadOS 17.6.1 for nearly a week. I tried sideloading TikTok++ and this error suddenly appeared. I have been trying to fix this error for the past 2 days but can’t fix it.

### Instructions to reproduce

1. Install SideStore with AltServer
2. Use it for a few days
3. Try sideloading/installing any app

### What version of SideStore are you using?

0.5.7

**Comment by junepark678** [comment] 2024-08-20 08:50
duplicate of #156

**Closed by junepark678** 2024-08-20 08:50 UTC
Labels: bug
