### ISSUE TITLE
Not receiving the code on SideStore

### ISSUE THREAD

**Issue by MrKhalid77** [SideStore/SideStore#707] opened 2024-10-07 19:17 UTC
### Describe the bug

After i write my Apple ID and the Password and press Sign in the the 6-digit verification code i don't receive the verification message.

i tried on the AltStore and i sign out and re-sign in and i received the code from Apple!
but when i tried in SideStore it’s Not
![IMG_8831](https://github.com/user-attachments/assets/70dcb8e5-9206-471a-bd44-4e04987d3bac)

### Instructions to reproduce

like i said 👆🏻

### What version of SideStore are you using?

0.5.8 - Xcode 1420 - 14C18

**Comment by kaoneko** [comment] 2024-10-16 23:43
Workaround: https://github.com/SideStore/SideStore/issues/605#issuecomment-2058173859

When your Apple account uses physical security keys instead of 6-digit verification codes, you'll have to remove them and re-add them later: https://github.com/SideStore/SideStore/issues/605#issuecomment-2293117271

**Comment by MrKhalid77** [comment] 2024-10-20 16:26
> Workaround: https://github.com/SideStore/SideStore/issues/605#issuecomment-2058173859
> 
> 
> 
> When your Apple account uses physical security keys instead of 6-digit verification codes, you'll have to remove them and re-add them later: https://github.com/SideStore/SideStore/issues/605#issuecomment-2293117271

How?

**Comment by kaoneko** [comment] 2024-10-21 00:02
Remove them as a 2FA method from your Apple account in the same screen were you once added them. But from your first post I gather you're not using physical security keys for 2FA, so it doesn't apply to you.

**Comment by junepark678** [comment] 2024-10-21 07:19
duplicate of #605

**Closed by junepark678** 2024-10-21 07:19 UTC
Labels: bug

**Comment by MrKhalid77** [comment] 2024-10-22 05:03
So, there is no solution, the problem persists.

**Comment by MrKhalid77** [comment] 2024-10-22 05:03
this's BAD

i will delete it

fuck it

**Comment by junepark678** [comment] 2024-10-22 07:10
cussing us out is not the way
