### ISSUE TITLE
[BUG] SideStore August 2024 update shows October 2023 update as new

### ISSUE THREAD

**Issue by FxRe** [SideStore/SideStore#666] opened 2024-08-08 17:01 UTC
### Describe the bug

I recently updated to the latest version, 0.5.7, which was described as August update. Today I noticed that SideStore shows an update as available, but that “new” version is the old October 23 update. I didn’t try to update. 

### Instructions to reproduce

Install 0.5.7, watch the old update become available. 

### What version of SideStore are you using?

0.5.7

**Comment by yodaluca23** [comment] 2024-08-08 17:16
This was made as a bug in the announcements on their discord channel. What I believe the issue is at least from my experience in using other sources with SideStore is that it won't update very often you can usually force it on a third-party source by deleting it and re-adding it obviously you can't do that with the internal source so yeah, they will be fixed in the next update according to the announcements on the discord server...

**Comment by FxRe** [comment] 2024-08-08 18:58
Oh, I see. Thanks. Posting the full announcement, in case someone else is curious:

> for any of you using latest SideStore, there seems to be a bug that keeps the last update pop up in the SideStore app. This will get fixed. When the fix comes you will likely need to sideload the ipa manually. Sorry for the inconvenience. 
Other than that it has a good amount of fixes that the last version needed that you will likely enjoy.

**Comment by Spidy123222** [comment] 2024-08-15 02:06
Yeah this was announced in the discord. It's currently a known issue

**Comment by nythepegasus** [comment] 2024-08-16 12:25
Hello this should be resolved now, if not you can reopen this issue.

**Comment by FxRe** [comment] 2024-08-17 06:46
Apologies, but this doesn’t seem to be fixed for me. I had to reinstall SideStore using SideServer due to another issue, it then immediately showed the April 2024 update. I installed that, SideStore still reports being 0.5.7, and now shows the November 2023 update as newly available.

**Comment by sasagr** [comment] 2024-08-18 13:20
![IMG_4409](https://github.com/user-attachments/assets/f74608ef-eaad-418b-8058-529649fd5ba4)
![IMG_4408](https://github.com/user-attachments/assets/5d06a200-c47a-4a0a-a7c9-40586d2089d8)

same here with the last nightly announced ipa, installed from within sidestore old version

**Comment by FxRe** [comment] 2024-08-24 10:19
Yup, I also tried the latest nightly (2024.08.19), which shows the same behavior. For some reason it displays a different version as latest update (November 23).

**Comment by sasagr** [comment] 2024-09-08 05:19
> ![IMG_4409](https://private-user-images.githubusercontent.com/3427877/358908806-f74608ef-eaad-418b-8058-529649fd5ba4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzI5ODcsIm5iZiI6MTcyNTc3MjY4NywicGF0aCI6Ii8zNDI3ODc3LzM1ODkwODgwNi1mNzQ2MDhlZi1lYWFkLTQxOGItODA1OC01Mjk2NDlmZDViYTQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA1MTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNDBmMDMxNTU1NGZiZjAzZDI2ZWQ4MmVlNjgzZmIzZTE1ZjBkOTU5YjkzY2NlNGU3OGJlNGE4ZjA1YmU1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JSoGAqkq9GhbHCPJ4lfGn4NcLuA5DrLxIwujsyOiIOc) ![IMG_4408](https://private-user-images.githubusercontent.com/3427877/358908810-5d06a200-c47a-4a0a-a7c9-40586d2089d8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzI5ODcsIm5iZiI6MTcyNTc3MjY4NywicGF0aCI6Ii8zNDI3ODc3LzM1ODkwODgxMC01ZDA2YTIwMC1jNDdhLTRhMGEtYTdjOS00MDU4NmQyMDg5ZDguanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA1MTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTFjNzhkNzc1NDhiNjk3MmY1NDdlMDllYTg1NDJhMDhjZjlmNjY3NDBhZDIwNjc5YTUxNDUyY2JlYWIzMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVtQtWfhsZNLOKzWNzxWewvEB0BC4Jgv8WBN3rzCGjk)
> 
> same here with the last nightly announced ipa, installed from within sidestore old version using +

I continue to have the same issue also with the 0.5.8 stable

**Comment by wamuumu** [comment] 2024-09-08 09:49
Do you guys know why my SideStore doesn't show anything under the updates section? I'm currently using version 0.5.7, and I wish to update to 0.5.8. Since nothing showed, I tried to manually install the SideStore .ipa using SideStore, but the app crashes. Am I missing something?

**Comment by yodaluca23** [comment] 2024-09-08 15:10
> Do you guys know why my SideStore doesn't show anything under the updates section? I'm currently using version 0.5.7, and I wish to update to 0.5.8. Since nothing showed, I tried to manually install the SideStore .ipa using SideStore, but the app crashes. Am I missing something?

Force close the app, and reopen it and try again.

**Comment by Staubgeborener** [comment] 2024-09-19 19:37
Can someone open this issue? It still exists (tested with version 0.5.8).

**Comment by aaronliu0130** [comment] 2024-10-11 22:34
@nythepegasus @SideStore Since this has been confirmed unresolved in the Discord server, can this please be reopened? Thank you.

**Comment by polymo1** [comment] 2024-10-11 22:45
Sure

**Comment by mahee96** [comment] 2024-10-18 22:57
#### This annoying thing got me digging into the source code...

### Anyways for the RCA: 
1. Issue is possibly due to Regression? caused by merging PR#616.
2. In `AltStoreCore/Model/InstalledApp.swift`, The `updatesFetchRequest`() logic had been changed to use a different check rather than the property `hasUpdate: Boolean`, which was being used earlier, so that both are in sync.

### Code Reference
https://github.com/SideStore/SideStore/blob/867a9c77e652b0a0f3a06cad4a1b4b2cdde89d83/AltStoreCore/Model/InstalledApp.swift#L166

### Commit id is shown below:
![image](https://github.com/user-attachments/assets/49023531-dbdf-439f-86d6-d2db628daa0d)


### Fix:
Reverting it to use `hasUpdate` fixes it but not sure if this was intentional change by the team. So the team should decide on the final fix or make enhancements.

**Comment by polymo1** [comment] 2024-10-18 23:06
@SideStore/project-maintainers cc!

**Closed** 2024-11-04 08:38 UTC
Labels: bug, help wanted
