### ISSUE TITLE
File does not exist error 

### ISSUE THREAD

**Issue by S3rialthrilla** [SideStore/SideStore#226] opened 2023-01-17 19:57 UTC
Using latest sideserver on macos I installed side store on my 12 mini and when sharing .ipa files on sidestore I get "The file does not exist " error. Had to revert to previous build of sideserver /sidestore to fix. Ios 15.5

**Comment by naturecodevoid** [comment] 2023-01-22 01:18
Seems to be a duplicate of https://github.com/SideStore/SideStore/issues/193

**Closed by naturecodevoid** 2023-01-22 01:18 UTC
Labels: bug
