### ISSUE TITLE
[BUG] Still being prompted for update even on latest version 

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#671] opened 2024-08-11 05:32 UTC
### Describe the bug

SideStore is still telling me to update even though I have the latest version installed. 

### Instructions to reproduce

Install SideStore 0.5.7 and it should be immediately obvious with the update being visible on the app icon and inside of the app. 

![IMG_2230](https://github.com/user-attachments/assets/2f3c6bd5-0573-4a7e-bc4d-8af28ab39a4f)
![IMG_2231](https://github.com/user-attachments/assets/9962d97a-6e71-46d8-8cc9-0b0054145650)

### What version of SideStore are you using?

0.5.7

**Comment by yodaluca23** [comment] 2024-08-11 06:21
Duplicate of #666

**Comment by VenomousSteam81** [comment] 2024-08-11 06:24
😭 why does issue #666 exist

**Comment by polymo1** [comment] 2024-08-11 13:32
> 😭 why does issue #666 exist 

Because github doesn't discriminate on numbers.

**Closed** 2024-08-11 13:32 UTC
Labels: bug
