### ISSUE TITLE
[BUG] Crashing after trying to install large file

### ISSUE THREAD

**Issue by Joshua-Mola** [SideStore/SideStore#545] opened 2023-11-26 18:41 UTC
### Describe the bug

When I try to install it, after a couple minutes the app just collapses on me. I think the problem is just that the file size is too big. Not sure tho

Specs: iPad 9 completely stock

file size 641 megabytes 

### Instructions to reproduce

Try to install a file 641 megabytes or larger
Try lowering the file size until it stops crashing

### What version of SideStore are you using?

0.5.3 Nightly

**Comment by junepark678** [comment] 2023-11-28 05:58
Duplicate of #170

**Closed by junepark678** 2023-11-28 05:58 UTC
Labels: bug
