### ISSUE TITLE
[BUG] crashes days after install

### ISSUE THREAD

**Issue by zac-massey** [SideStore/SideStore#588] opened 2024-03-01 13:15 UTC
### Describe the bug

I installed SideStore, the next day it wouldn’t open and would crash. I had reinstalled it and now it’s working but not sure when it’ll crash again. 

### Instructions to reproduce

Install, wait a few darts, crash, reinstall

### What version of SideStore are you using?

0.5.4

**Comment by WesleyBryie** [comment] 2024-03-01 17:15
This is a known issue and is caused by not refreshing SideStore after install, as mentioned in the wiki. Please reinstall SideStore: using AltServer, following the wiki, and having refreshed SideStore after install.

**Comment by WesleyBryie** [comment] 2024-04-01 21:56
Please let us know if you have any further issues. For now I'm closing this as this is a well known issue.

**Closed by WesleyBryie** 2024-04-01 21:56 UTC
Labels: bug
