### ISSUE TITLE
SideStore exits too early when using Refresh All

### ISSUE THREAD

**Issue by reticivis-net** [SideStore/SideStore#359] opened 2023-05-07 02:50 UTC
### Describe the bug

When hitting “refresh all”, sidestore exits after the first app refreshes and fails to refresh any other apps

### Instructions to reproduce

Install multiple apps
Refresh All

### What version of SideStore are you using?

SideStore 0.3.2-pr.324+ad66ebc

### Other info

I understand that exiting is for some reason a part of the sidestore refreshing process but i feel that it could be possible to refresh all apps and then exit to let them all refresh properly

**Comment by naturecodevoid** [comment] 2023-05-07 14:22
either a regression was introduced or you are not using the refresh all button. I specifically tested this and I made sure that sidestore waited until the other apps finished refreshing to reinstall.

**Comment by HexCodeFFF** [comment] 2023-05-23 02:12
https://github.com/SideStore/SideStore/assets/35177464/000660a4-776e-4ade-99de-e44bb8ee4342

**Comment by HexCodeFFF** [comment] 2023-05-23 02:14
weirdly enough, the Shortcuts "refresh all" action seems to work fine. the reason I'm so late to reply is that my automation to auto-refresh all has worked so well that my apps never went below 7 days, making it hard to tell if an app got refreshed or not. finally got the chance to showcase this bug when the pairing file expired lol

**Comment by Paari15** [comment] 2024-07-19 13:19
> trim.C2820037-093C-49AC-9A63-E95A10CE69BF.MOV

found the solution just one step
Step 1: Just remove the side store widget from Home Screen, after that it will work fine.

**Comment by Spidy123222** [comment] 2024-08-15 01:13
This is a refresh crash and will get solved eventually.

**Comment by junepark678** [comment] 2024-09-03 07:32
i think this is mostly fixed now

**Closed by junepark678** 2024-09-03 07:32 UTC
Labels: bug
