### ISSUE TITLE
[bundle id User-defined function]

### ISSUE THREAD

**Issue by zmyLiuFeng** [SideStore/SideStore#263] opened 2023-02-13 15:58 UTC
User-defined function
I know that the IPA bundle id cannot conflict with the bundle id in the App Store, but we can add a logic that says,
1.  If the entered bundle ids conflict, the bundle ids are automatically generated.  If the entered bundle ids do not conflict, the entered bundle ids are used

Because I've found that many developer signing tools have different rules for generating package ids, such as
Default ipa bundle id:com.facebook.test
Bullfrog :* * * *.com.facebook.test
sideloadly :com.facebook.test.* * * *
sideStore: com.  * * * *.facebook.test

What is the impact of bundle id differences?
Some company programs prefix the bundle id ! = com.facebook.test * * * *
Turning on IPA will result in an error with no network

**Comment by naturecodevoid** [comment] 2023-02-13 16:10
Duplicate of #233

I will put your suggestions in that issue.

**Closed** 2023-02-13 16:11 UTC
Labels: enhancement

**Comment by zmyLiuFeng** [comment] 2023-02-13 16:20
> I will put your suggestions in that issue.

OK,Thank you and your team for your contribution and dedication.
