### ISSUE TITLE
[BUG] Crash when trying to install anything

### ISSUE THREAD

**Issue by VSS-Vintorez** [SideStore/SideStore#471] opened 2023-09-18 06:37 UTC
### Describe the bug

When trying to install any app, it crashes, and in the minimuxer log, the last line is `minimuxer::install: installing`, and the last thing it shows in idevicedebug is `Exit due to signal: 9`

### Instructions to reproduce

Install the IPA through AltServer, and try to refresh SideStore, or install any app

### What version of SideStore are you using?

0.5.1-nightly.2023.09.18.1_44125a5 (MDC)

### Other info

iPhone13,2 iOS 15.5 RC (19F77)

**Comment by VSS-Vintorez** [comment] 2023-09-18 06:44
Here's the whole idevicedebug log
[idevicedebug.log](https://github.com/SideStore/SideStore/files/12645193/idevicedebug.log)

**Comment by VSS-Vintorez** [comment] 2023-09-18 06:57
It worked on 0.4.0 and 0.5.0, so must be a new issue?

**Comment by VSS-Vintorez** [comment] 2023-09-18 07:51
[SideStore-2023-09-18-004213.zip](https://github.com/SideStore/SideStore/files/12645590/SideStore-2023-09-18-004213.zip)
Here's the log from Analytics

**Comment by the-duck2010** [comment] 2023-09-18 11:13
Having the same problem on stable.

**Comment by Vykonn** [comment] 2023-09-18 11:40
i am having the exact same problem, on 0.5.1.

**Comment by naturecodevoid** [comment] 2023-09-18 14:53
Could someone give a crash report from 0.5.1 without MDC?

**Comment by VSS-Vintorez** [comment] 2023-09-18 21:35
I can't get an analytics report on it yet, but it looks the same with idevicedebug @naturecodevoid

**Comment by the-duck2010** [comment] 2023-09-18 21:42
ios 15.5, sidestore 0.5.1, installed w/ altstore.

[SideStore-2023-09-17-213730.zip](https://github.com/SideStore/SideStore/files/12653714/SideStore-2023-09-17-213730.zip)

**Comment by VSS-Vintorez** [comment] 2023-09-18 21:46
Also it's worth noting my account was locked and unlocked a few days ago.

**Comment by VSS-Vintorez** [comment] 2023-09-18 22:20
The app works just fine on 0.5.0, but 0.5.1 is when it crashes.

**Comment by naturecodevoid** [comment] 2023-09-18 22:30
I have not experienced the crash. You sent a crash report from MDC SideStore, and I needed one from normal SideStore. Someone sent one from normal SideStore. I'll look into this crash later if I have time.

**Comment by VSS-Vintorez** [comment] 2023-09-18 22:41
The non MDC version was not generating logs, that's why

**Comment by naturecodevoid** [comment] 2023-09-18 22:55
I believe I've determined where the crash occurs. @the-duck2010 have you uninstalled AltStore?

**Comment by the-duck2010** [comment] 2023-09-18 23:06
No I have not, was I supposed to do that?

**Comment by naturecodevoid** [comment] 2023-09-18 23:07
AltStore can cause SideStore to crash. However, I checked the MDC crash report and you both have the same crash, so it's most likely not caused by AltStore

**Comment by the-duck2010** [comment] 2023-09-18 23:08
Let me uninstall it and I will let you know if it fixes anything.

**Comment by naturecodevoid** [comment] 2023-09-18 23:21
I've pushed a potential fix and I am waiting for minimuxer and then nightly to build. I will send a link to the nightly build once it finishes building

**Comment by naturecodevoid** [comment] 2023-09-18 23:36
@the-duck2010 @VSS-Vintorez @Vykonn Let me know if this fixes it (scroll down and download the IPA, then sideload it in SideStore or using SideServer/AltServer): https://github.com/SideStore/SideStore/actions/runs/6229118533

**Comment by the-duck2010** [comment] 2023-09-19 00:59
Sidestore just throws an error with the new version. ![image](https://github.com/SideStore/SideStore/assets/75392757/68fd4aba-a510-44d4-9600-6e4c7f78b2d7)

**Comment by naturecodevoid** [comment] 2023-09-19 02:04
What did you use to sideload it?

**Comment by the-duck2010** [comment] 2023-09-19 02:19
Sideloadly since Altstore was being weird. I seem to remember that being an option on the wiki.

**Comment by naturecodevoid** [comment] 2023-09-19 02:40
Sideloadly is currently not supported

**Comment by the-duck2010** [comment] 2023-09-19 10:40
Ok, I will try using Altstore again.

**Comment by the-duck2010** [comment] 2023-09-19 11:01
Patched!

**Comment by naturecodevoid** [comment] 2023-09-19 13:42
Someone in discord is still reporting a crash but no crash report is appearing, so please send a crash report if you still get it after the fix

**Comment by the-duck2010** [comment] 2023-09-20 00:56
When will a MDC build with the patch be available?

**Comment by Vykonn** [comment] 2023-09-20 01:12
> When will a MDC build with the patch be available?

[0.5.2 w/ MDC](https://github.com/preland/SideStore/actions/runs/6235658607)
I believe this build should have MDC.
Also, this issue may relate to [Discord - support-forum - Crashes when refreshing SideStore](https://discord.com/channels/949183273383395328/1153127737855320094), that's where i got this build from.

**Comment by naturecodevoid** [comment] 2023-09-20 14:03
Please send the crash report!!

**Comment by CastanaEddd** [comment] 2023-09-24 01:04
Had the same issue, after upgrading to the 0.5.2-nightly release seems to be working fine. Including the the MDC build posted above. Side-loaded with [AltServer-Linux](https://github.com/NyaMisty/AltServer-Linux)

**Comment by naturecodevoid** [comment] 2023-09-29 01:55
Closing as fixed. If you still experience the issue on 0.5.2 (nightly builds or stable once that's out) send a crash report here and I'll reopen it

**Closed by naturecodevoid** 2023-09-29 01:55 UTC
Labels: bug
